# Regenerates Autotech.Desktop.Setup\ProductFiles.wxs from the published output.
#
# Run this after 'dotnet publish' and before building the WiX project - version.ps1
# does both, in that order. Everything under the publish folder is included, including
# the satellite resource subdirectories.
#
# Notes on the generated markup:
#   * Identifiers are sanitised. A file name can contain characters that are legal on
#     disk but illegal in a WiX Id - for example the space in "MetroSet UI.dll".
#   * Ids are derived from the path relative to the publish root, not from the file
#     name. The locale subfolders reuse names such as System.Windows.Forms.resources.dll,
#     and duplicate Ids fail the link step.
#   * Components use Guid='*' so WiX derives a stable GUID from the install location.
#     Minting a fresh GUID on every run breaks MSI component rules, which surfaces later
#     as orphaned files and failed repairs after an upgrade.

param(
    [string]$PublishPath = "$PSScriptRoot\Autotech.Desktop.Main\bin\Release\net10.0-windows7.0\win-x64\publish",
    [string]$OutputWxs   = "$PSScriptRoot\Autotech.Desktop.Setup\ProductFiles.wxs"
)

if (-not (Test-Path $PublishPath)) {
    throw "Publish folder not found: $PublishPath`nRun 'dotnet publish -c Release -r win-x64 --self-contained true' first."
}

$PublishPath = (Resolve-Path $PublishPath).Path.TrimEnd('\')

function Get-SafeId {
    param([string]$Text)
    $safe = [regex]::Replace($Text, '[^A-Za-z0-9_.]', '_')
    if ($safe -notmatch '^[A-Za-z_]') { $safe = "_$safe" }
    return $safe
}

$componentRefs = New-Object System.Collections.Generic.List[string]

function Write-DirectoryTree {
    param([string]$Path, [string]$RelativePrefix, [int]$Indent)

    $pad = ' ' * $Indent
    $sb = New-Object System.Text.StringBuilder

    foreach ($file in (Get-ChildItem -Path $Path -File | Sort-Object Name)) {
        $relative = if ($RelativePrefix) { "$RelativePrefix\$($file.Name)" } else { $file.Name }
        $componentId = Get-SafeId "Comp_$relative"
        $fileId = Get-SafeId "File_$relative"

        $componentRefs.Add("      <ComponentRef Id='$componentId' />")
        [void]$sb.AppendLine("$pad<Component Id='$componentId' Guid='*'>")
        [void]$sb.AppendLine("$pad  <File Id='$fileId' Source='`$(var.PublishDir)$relative' KeyPath='yes' />")
        [void]$sb.AppendLine("$pad</Component>")
    }

    foreach ($dir in (Get-ChildItem -Path $Path -Directory | Sort-Object Name)) {
        $relative = if ($RelativePrefix) { "$RelativePrefix\$($dir.Name)" } else { $dir.Name }
        $directoryId = Get-SafeId "Dir_$relative"

        [void]$sb.AppendLine("$pad<Directory Id='$directoryId' Name='$($dir.Name)'>")
        [void]$sb.Append((Write-DirectoryTree -Path $dir.FullName -RelativePrefix $relative -Indent ($Indent + 2)))
        [void]$sb.AppendLine("$pad</Directory>")
    }

    return $sb.ToString()
}

$tree = Write-DirectoryTree -Path $PublishPath -RelativePrefix '' -Indent 6

$wxsContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by GenerateFiles.ps1 - do not edit by hand. -->
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Fragment>
    <DirectoryRef Id="INSTALLFOLDER">
$tree    </DirectoryRef>

    <ComponentGroup Id="ProductComponents">
$($componentRefs -join "`n")
    </ComponentGroup>
  </Fragment>
</Wix>
"@

Set-Content -Path $OutputWxs -Value $wxsContent -Encoding UTF8
Write-Host "ProductFiles.wxs generated at $OutputWxs ($($componentRefs.Count) components from $PublishPath)"
